/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ABackPBack extends PPBack
{
    private TBack _back_;
    private PPValue _pValue_;

    public ABackPBack()
    {
        // Constructor
    }

    public ABackPBack(
        @SuppressWarnings("hiding") TBack _back_,
        @SuppressWarnings("hiding") PPValue _pValue_)
    {
        // Constructor
        setBack(_back_);

        setPValue(_pValue_);

    }

    @Override
    public Object clone()
    {
        return new ABackPBack(
            cloneNode(this._back_),
            cloneNode(this._pValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABackPBack(this);
    }

    public TBack getBack()
    {
        return this._back_;
    }

    public void setBack(TBack node)
    {
        if(this._back_ != null)
        {
            this._back_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._back_ = node;
    }

    public PPValue getPValue()
    {
        return this._pValue_;
    }

    public void setPValue(PPValue node)
    {
        if(this._pValue_ != null)
        {
            this._pValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._back_)
            + toString(this._pValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._back_ == child)
        {
            this._back_ = null;
            return;
        }

        if(this._pValue_ == child)
        {
            this._pValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._back_ == oldChild)
        {
            setBack((TBack) newChild);
            return;
        }

        if(this._pValue_ == oldChild)
        {
            setPValue((PPValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
