/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AClrPGraphics extends PPGraphics
{
    private PPClearscreen _pClearscreen_;

    public AClrPGraphics()
    {
        // Constructor
    }

    public AClrPGraphics(
        @SuppressWarnings("hiding") PPClearscreen _pClearscreen_)
    {
        // Constructor
        setPClearscreen(_pClearscreen_);

    }

    @Override
    public Object clone()
    {
        return new AClrPGraphics(
            cloneNode(this._pClearscreen_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClrPGraphics(this);
    }

    public PPClearscreen getPClearscreen()
    {
        return this._pClearscreen_;
    }

    public void setPClearscreen(PPClearscreen node)
    {
        if(this._pClearscreen_ != null)
        {
            this._pClearscreen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pClearscreen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pClearscreen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pClearscreen_ == child)
        {
            this._pClearscreen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pClearscreen_ == oldChild)
        {
            setPClearscreen((PPClearscreen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
