/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ADifListPDifList extends PPDifList
{
    private TMin _min_;
    private PPValue _pValue_;
    private PPDifList _pDifList_;

    public ADifListPDifList()
    {
        // Constructor
    }

    public ADifListPDifList(
        @SuppressWarnings("hiding") TMin _min_,
        @SuppressWarnings("hiding") PPValue _pValue_,
        @SuppressWarnings("hiding") PPDifList _pDifList_)
    {
        // Constructor
        setMin(_min_);

        setPValue(_pValue_);

        setPDifList(_pDifList_);

    }

    @Override
    public Object clone()
    {
        return new ADifListPDifList(
            cloneNode(this._min_),
            cloneNode(this._pValue_),
            cloneNode(this._pDifList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADifListPDifList(this);
    }

    public TMin getMin()
    {
        return this._min_;
    }

    public void setMin(TMin node)
    {
        if(this._min_ != null)
        {
            this._min_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._min_ = node;
    }

    public PPValue getPValue()
    {
        return this._pValue_;
    }

    public void setPValue(PPValue node)
    {
        if(this._pValue_ != null)
        {
            this._pValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pValue_ = node;
    }

    public PPDifList getPDifList()
    {
        return this._pDifList_;
    }

    public void setPDifList(PPDifList node)
    {
        if(this._pDifList_ != null)
        {
            this._pDifList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pDifList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._min_)
            + toString(this._pValue_)
            + toString(this._pDifList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._min_ == child)
        {
            this._min_ = null;
            return;
        }

        if(this._pValue_ == child)
        {
            this._pValue_ = null;
            return;
        }

        if(this._pDifList_ == child)
        {
            this._pDifList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._min_ == oldChild)
        {
            setMin((TMin) newChild);
            return;
        }

        if(this._pValue_ == oldChild)
        {
            setPValue((PPValue) newChild);
            return;
        }

        if(this._pDifList_ == oldChild)
        {
            setPDifList((PPDifList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
