/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AExpPArithmetic extends PPArithmetic
{
    private PPExp _pExp_;

    public AExpPArithmetic()
    {
        // Constructor
    }

    public AExpPArithmetic(
        @SuppressWarnings("hiding") PPExp _pExp_)
    {
        // Constructor
        setPExp(_pExp_);

    }

    @Override
    public Object clone()
    {
        return new AExpPArithmetic(
            cloneNode(this._pExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpPArithmetic(this);
    }

    public PPExp getPExp()
    {
        return this._pExp_;
    }

    public void setPExp(PPExp node)
    {
        if(this._pExp_ != null)
        {
            this._pExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pExp_ == child)
        {
            this._pExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pExp_ == oldChild)
        {
            setPExp((PPExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
