/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AFirstPSelectors extends PPSelectors
{
    private PPFirst _pFirst_;

    public AFirstPSelectors()
    {
        // Constructor
    }

    public AFirstPSelectors(
        @SuppressWarnings("hiding") PPFirst _pFirst_)
    {
        // Constructor
        setPFirst(_pFirst_);

    }

    @Override
    public Object clone()
    {
        return new AFirstPSelectors(
            cloneNode(this._pFirst_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFirstPSelectors(this);
    }

    public PPFirst getPFirst()
    {
        return this._pFirst_;
    }

    public void setPFirst(PPFirst node)
    {
        if(this._pFirst_ != null)
        {
            this._pFirst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pFirst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pFirst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pFirst_ == child)
        {
            this._pFirst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pFirst_ == oldChild)
        {
            setPFirst((PPFirst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
