/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AGotoPControlStructures extends PPControlStructures
{
    private PPGoto _pGoto_;

    public AGotoPControlStructures()
    {
        // Constructor
    }

    public AGotoPControlStructures(
        @SuppressWarnings("hiding") PPGoto _pGoto_)
    {
        // Constructor
        setPGoto(_pGoto_);

    }

    @Override
    public Object clone()
    {
        return new AGotoPControlStructures(
            cloneNode(this._pGoto_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGotoPControlStructures(this);
    }

    public PPGoto getPGoto()
    {
        return this._pGoto_;
    }

    public void setPGoto(PPGoto node)
    {
        if(this._pGoto_ != null)
        {
            this._pGoto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pGoto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pGoto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pGoto_ == child)
        {
            this._pGoto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pGoto_ == oldChild)
        {
            setPGoto((PPGoto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
