/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AGraphicsPInstruction extends PPInstruction
{
    private PPGraphics _pGraphics_;

    public AGraphicsPInstruction()
    {
        // Constructor
    }

    public AGraphicsPInstruction(
        @SuppressWarnings("hiding") PPGraphics _pGraphics_)
    {
        // Constructor
        setPGraphics(_pGraphics_);

    }

    @Override
    public Object clone()
    {
        return new AGraphicsPInstruction(
            cloneNode(this._pGraphics_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGraphicsPInstruction(this);
    }

    public PPGraphics getPGraphics()
    {
        return this._pGraphics_;
    }

    public void setPGraphics(PPGraphics node)
    {
        if(this._pGraphics_ != null)
        {
            this._pGraphics_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pGraphics_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pGraphics_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pGraphics_ == child)
        {
            this._pGraphics_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pGraphics_ == oldChild)
        {
            setPGraphics((PPGraphics) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
