/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AHomePGraphics extends PPGraphics
{
    private PPHome _pHome_;

    public AHomePGraphics()
    {
        // Constructor
    }

    public AHomePGraphics(
        @SuppressWarnings("hiding") PPHome _pHome_)
    {
        // Constructor
        setPHome(_pHome_);

    }

    @Override
    public Object clone()
    {
        return new AHomePGraphics(
            cloneNode(this._pHome_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHomePGraphics(this);
    }

    public PPHome getPHome()
    {
        return this._pHome_;
    }

    public void setPHome(PPHome node)
    {
        if(this._pHome_ != null)
        {
            this._pHome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pHome_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pHome_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pHome_ == child)
        {
            this._pHome_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pHome_ == oldChild)
        {
            setPHome((PPHome) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
