/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AParentesisPOperation extends PPOperation
{
    private TLPar _lPar_;
    private PPOperation _pOperation_;
    private TRPar _rPar_;

    public AParentesisPOperation()
    {
        // Constructor
    }

    public AParentesisPOperation(
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PPOperation _pOperation_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setLPar(_lPar_);

        setPOperation(_pOperation_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new AParentesisPOperation(
            cloneNode(this._lPar_),
            cloneNode(this._pOperation_),
            cloneNode(this._rPar_));
    }

    public void apply(Switch sw)
    {
    	//problem  ((Analysis) sw).caseAParentesisPOperation(this);
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PPOperation getPOperation()
    {
        return this._pOperation_;
    }

    public void setPOperation(PPOperation node)
    {
        if(this._pOperation_ != null)
        {
            this._pOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pOperation_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lPar_)
            + toString(this._pOperation_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._pOperation_ == child)
        {
            this._pOperation_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._pOperation_ == oldChild)
        {
            setPOperation((PPOperation) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
