/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class APdPPencontrol extends PPPencontrol
{
    private PPPendown _pPendown_;

    public APdPPencontrol()
    {
        // Constructor
    }

    public APdPPencontrol(
        @SuppressWarnings("hiding") PPPendown _pPendown_)
    {
        // Constructor
        setPPendown(_pPendown_);

    }

    @Override
    public Object clone()
    {
        return new APdPPencontrol(
            cloneNode(this._pPendown_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPdPPencontrol(this);
    }

    public PPPendown getPPendown()
    {
        return this._pPendown_;
    }

    public void setPPendown(PPPendown node)
    {
        if(this._pPendown_ != null)
        {
            this._pPendown_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pPendown_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pPendown_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pPendown_ == child)
        {
            this._pPendown_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pPendown_ == oldChild)
        {
            setPPendown((PPPendown) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
