/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class APenctrlPGraphics extends PPGraphics
{
    private PPPencontrol _pPencontrol_;

    public APenctrlPGraphics()
    {
        // Constructor
    }

    public APenctrlPGraphics(
        @SuppressWarnings("hiding") PPPencontrol _pPencontrol_)
    {
        // Constructor
        setPPencontrol(_pPencontrol_);

    }

    @Override
    public Object clone()
    {
        return new APenctrlPGraphics(
            cloneNode(this._pPencontrol_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPenctrlPGraphics(this);
    }

    public PPPencontrol getPPencontrol()
    {
        return this._pPencontrol_;
    }

    public void setPPencontrol(PPPencontrol node)
    {
        if(this._pPencontrol_ != null)
        {
            this._pPencontrol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pPencontrol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pPencontrol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pPencontrol_ == child)
        {
            this._pPencontrol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pPencontrol_ == oldChild)
        {
            setPPencontrol((PPPencontrol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
