/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class APOr extends PPOr
{
    private TOr _or_;
    private PPBoolean _v1_;
    private PPBoolean _v2_;

    public APOr()
    {
        // Constructor
    }

    public APOr(
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PPBoolean _v1_,
        @SuppressWarnings("hiding") PPBoolean _v2_)
    {
        // Constructor
        setOr(_or_);

        setV1(_v1_);

        setV2(_v2_);

    }

    @Override
    public Object clone()
    {
        return new APOr(
            cloneNode(this._or_),
            cloneNode(this._v1_),
            cloneNode(this._v2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPOr(this);
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PPBoolean getV1()
    {
        return this._v1_;
    }

    public void setV1(PPBoolean node)
    {
        if(this._v1_ != null)
        {
            this._v1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._v1_ = node;
    }

    public PPBoolean getV2()
    {
        return this._v2_;
    }

    public void setV2(PPBoolean node)
    {
        if(this._v2_ != null)
        {
            this._v2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._v2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._or_)
            + toString(this._v1_)
            + toString(this._v2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._v1_ == child)
        {
            this._v1_ = null;
            return;
        }

        if(this._v2_ == child)
        {
            this._v2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._v1_ == oldChild)
        {
            setV1((PPBoolean) newChild);
            return;
        }

        if(this._v2_ == oldChild)
        {
            setV2((PPBoolean) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
