/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class APusPPencontrol extends PPPencontrol
{
    private PPPenup _pPenup_;

    public APusPPencontrol()
    {
        // Constructor
    }

    public APusPPencontrol(
        @SuppressWarnings("hiding") PPPenup _pPenup_)
    {
        // Constructor
        setPPenup(_pPenup_);

    }

    @Override
    public Object clone()
    {
        return new APusPPencontrol(
            cloneNode(this._pPenup_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPusPPencontrol(this);
    }

    public PPPenup getPPenup()
    {
        return this._pPenup_;
    }

    public void setPPenup(PPPenup node)
    {
        if(this._pPenup_ != null)
        {
            this._pPenup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pPenup_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pPenup_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pPenup_ == child)
        {
            this._pPenup_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pPenup_ == oldChild)
        {
            setPPenup((PPPenup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
