/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ARtPRight extends PPRight
{
    private TRt _rt_;
    private TInteger _integer_;

    public ARtPRight()
    {
        // Constructor
    }

    public ARtPRight(
        @SuppressWarnings("hiding") TRt _rt_,
        @SuppressWarnings("hiding") TInteger _integer_)
    {
        // Constructor
        setRt(_rt_);

        setInteger(_integer_);

    }

    @Override
    public Object clone()
    {
        return new ARtPRight(
            cloneNode(this._rt_),
            cloneNode(this._integer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARtPRight(this);
    }

    public TRt getRt()
    {
        return this._rt_;
    }

    public void setRt(TRt node)
    {
        if(this._rt_ != null)
        {
            this._rt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rt_ = node;
    }

    public TInteger getInteger()
    {
        return this._integer_;
    }

    public void setInteger(TInteger node)
    {
        if(this._integer_ != null)
        {
            this._integer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rt_)
            + toString(this._integer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rt_ == child)
        {
            this._rt_ = null;
            return;
        }

        if(this._integer_ == child)
        {
            this._integer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rt_ == oldChild)
        {
            setRt((TRt) newChild);
            return;
        }

        if(this._integer_ == oldChild)
        {
            setInteger((TInteger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
