/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AStopPControlStructures extends PPControlStructures
{
    private PPStop _pStop_;

    public AStopPControlStructures()
    {
        // Constructor
    }

    public AStopPControlStructures(
        @SuppressWarnings("hiding") PPStop _pStop_)
    {
        // Constructor
        setPStop(_pStop_);

    }

    @Override
    public Object clone()
    {
        return new AStopPControlStructures(
            cloneNode(this._pStop_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStopPControlStructures(this);
    }

    public PPStop getPStop()
    {
        return this._pStop_;
    }

    public void setPStop(PPStop node)
    {
        if(this._pStop_ != null)
        {
            this._pStop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pStop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pStop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pStop_ == child)
        {
            this._pStop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pStop_ == oldChild)
        {
            setPStop((PPStop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
