/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AVarnumPMake extends PPMake
{
    private TMake _make_;
    private TIdentifier _var_;
    private PPValue _valor_;

    public AVarnumPMake()
    {
        // Constructor
    }

    public AVarnumPMake(
        @SuppressWarnings("hiding") TMake _make_,
        @SuppressWarnings("hiding") TIdentifier _var_,
        @SuppressWarnings("hiding") PPValue _valor_)
    {
        // Constructor
        setMake(_make_);

        setVar(_var_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AVarnumPMake(
            cloneNode(this._make_),
            cloneNode(this._var_),
            cloneNode(this._valor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarnumPMake(this);
    }

    public TMake getMake()
    {
        return this._make_;
    }

    public void setMake(TMake node)
    {
        if(this._make_ != null)
        {
            this._make_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._make_ = node;
    }

    public TIdentifier getVar()
    {
        return this._var_;
    }

    public void setVar(TIdentifier node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PPValue getValor()
    {
        return this._valor_;
    }

    public void setValor(PPValue node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._make_)
            + toString(this._var_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._make_ == child)
        {
            this._make_ = null;
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._make_ == oldChild)
        {
            setMake((TMake) newChild);
            return;
        }

        if(this._var_ == oldChild)
        {
            setVar((TIdentifier) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PPValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
