/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TArc extends Token
{
    public TArc()
    {
        super.setText("ARC");
    }

    public TArc(int line, int pos)
    {
        super.setText("ARC");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArc(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArc text.");
    }
}
