/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TBk extends Token
{
    public TBk()
    {
        super.setText("BK");
    }

    public TBk(int line, int pos)
    {
        super.setText("BK");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBk(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBk(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBk text.");
    }
}
