/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TMake extends Token
{
    public TMake()
    {
        super.setText("MAKE");
    }

    public TMake(int line, int pos)
    {
        super.setText("MAKE");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMake(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMake(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMake text.");
    }
}
