/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TPendown extends Token
{
    public TPendown()
    {
        super.setText("PENDOWN");
    }

    public TPendown(int line, int pos)
    {
        super.setText("PENDOWN");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPendown(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPendown(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPendown text.");
    }
}
