/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TProcname extends Token
{
    public TProcname()
    {
        super.setText("PROCNAME");
    }

    public TProcname(int line, int pos)
    {
        super.setText("PROCNAME");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProcname(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProcname(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProcname text.");
    }
}
