/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ABfPButfirst extends PPButfirst
{
    private TBf _bf_;
    private TIdentifier _identifier_;

    public ABfPButfirst()
    {
        // Constructor
    }

    public ABfPButfirst(
        @SuppressWarnings("hiding") TBf _bf_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setBf(_bf_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new ABfPButfirst(
            cloneNode(this._bf_),
            cloneNode(this._identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABfPButfirst(this);
    }

    public TBf getBf()
    {
        return this._bf_;
    }

    public void setBf(TBf node)
    {
        if(this._bf_ != null)
        {
            this._bf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bf_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bf_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bf_ == child)
        {
            this._bf_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bf_ == oldChild)
        {
            setBf((TBf) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
