/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ABksPGraphics extends PPGraphics
{
    private PPBack _pBack_;

    public ABksPGraphics()
    {
        // Constructor
    }

    public ABksPGraphics(
        @SuppressWarnings("hiding") PPBack _pBack_)
    {
        // Constructor
        setPBack(_pBack_);

    }

    @Override
    public Object clone()
    {
        return new ABksPGraphics(
            cloneNode(this._pBack_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABksPGraphics(this);
    }

    public PPBack getPBack()
    {
        return this._pBack_;
    }

    public void setPBack(PPBack node)
    {
        if(this._pBack_ != null)
        {
            this._pBack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pBack_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pBack_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pBack_ == child)
        {
            this._pBack_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pBack_ == oldChild)
        {
            setPBack((PPBack) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
