/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AFdPGraphics extends PPGraphics
{
    private PPForward _pForward_;

    public AFdPGraphics()
    {
        // Constructor
    }

    public AFdPGraphics(
        @SuppressWarnings("hiding") PPForward _pForward_)
    {
        // Constructor
        setPForward(_pForward_);

    }

    @Override
    public Object clone()
    {
        return new AFdPGraphics(
            cloneNode(this._pForward_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFdPGraphics(this);
    }

    public PPForward getPForward()
    {
        return this._pForward_;
    }

    public void setPForward(PPForward node)
    {
        if(this._pForward_ != null)
        {
            this._pForward_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pForward_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pForward_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pForward_ == child)
        {
            this._pForward_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pForward_ == oldChild)
        {
            setPForward((PPForward) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
