/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AForwardPForward extends PPForward
{
    private TForward _forward_;
    private TInteger _integer_;

    public AForwardPForward()
    {
        // Constructor
    }

    public AForwardPForward(
        @SuppressWarnings("hiding") TForward _forward_,
        @SuppressWarnings("hiding") TInteger _integer_)
    {
        // Constructor
        setForward(_forward_);

        setInteger(_integer_);

    }

    @Override
    public Object clone()
    {
        return new AForwardPForward(
            cloneNode(this._forward_),
            cloneNode(this._integer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForwardPForward(this);
    }

    public TForward getForward()
    {
        return this._forward_;
    }

    public void setForward(TForward node)
    {
        if(this._forward_ != null)
        {
            this._forward_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forward_ = node;
    }

    public TInteger getInteger()
    {
        return this._integer_;
    }

    public void setInteger(TInteger node)
    {
        if(this._integer_ != null)
        {
            this._integer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forward_)
            + toString(this._integer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forward_ == child)
        {
            this._forward_ = null;
            return;
        }

        if(this._integer_ == child)
        {
            this._integer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forward_ == oldChild)
        {
            setForward((TForward) newChild);
            return;
        }

        if(this._integer_ == oldChild)
        {
            setInteger((TInteger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
