/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ALastPSelectors extends PPSelectors
{
    private PPLast _pLast_;

    public ALastPSelectors()
    {
        // Constructor
    }

    public ALastPSelectors(
        @SuppressWarnings("hiding") PPLast _pLast_)
    {
        // Constructor
        setPLast(_pLast_);

    }

    @Override
    public Object clone()
    {
        return new ALastPSelectors(
            cloneNode(this._pLast_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALastPSelectors(this);
    }

    public PPLast getPLast()
    {
        return this._pLast_;
    }

    public void setPLast(PPLast node)
    {
        if(this._pLast_ != null)
        {
            this._pLast_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pLast_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pLast_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pLast_ == child)
        {
            this._pLast_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pLast_ == oldChild)
        {
            setPLast((PPLast) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
