/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ALogicPInstruction extends PPInstruction
{
    private PPLogic _pLogic_;

    public ALogicPInstruction()
    {
        // Constructor
    }

    public ALogicPInstruction(
        @SuppressWarnings("hiding") PPLogic _pLogic_)
    {
        // Constructor
        setPLogic(_pLogic_);

    }

    @Override
    public Object clone()
    {
        return new ALogicPInstruction(
            cloneNode(this._pLogic_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicPInstruction(this);
    }

    public PPLogic getPLogic()
    {
        return this._pLogic_;
    }

    public void setPLogic(PPLogic node)
    {
        if(this._pLogic_ != null)
        {
            this._pLogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pLogic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pLogic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pLogic_ == child)
        {
            this._pLogic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pLogic_ == oldChild)
        {
            setPLogic((PPLogic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
