/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class APFirst extends PPFirst
{
    private TFirst _first_;
    private PPThing _pThing_;

    public APFirst()
    {
        // Constructor
    }

    public APFirst(
        @SuppressWarnings("hiding") TFirst _first_,
        @SuppressWarnings("hiding") PPThing _pThing_)
    {
        // Constructor
        setFirst(_first_);

        setPThing(_pThing_);

    }

    @Override
    public Object clone()
    {
        return new APFirst(
            cloneNode(this._first_),
            cloneNode(this._pThing_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPFirst(this);
    }

    public TFirst getFirst()
    {
        return this._first_;
    }

    public void setFirst(TFirst node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PPThing getPThing()
    {
        return this._pThing_;
    }

    public void setPThing(PPThing node)
    {
        if(this._pThing_ != null)
        {
            this._pThing_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pThing_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._pThing_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._pThing_ == child)
        {
            this._pThing_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((TFirst) newChild);
            return;
        }

        if(this._pThing_ == oldChild)
        {
            setPThing((PPThing) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
