/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class APModulo extends PPModulo
{
    private TModulo _modulo_;
    private PPModv _pModv_;
    private TInteger _integer_;

    public APModulo()
    {
        // Constructor
    }

    public APModulo(
        @SuppressWarnings("hiding") TModulo _modulo_,
        @SuppressWarnings("hiding") PPModv _pModv_,
        @SuppressWarnings("hiding") TInteger _integer_)
    {
        // Constructor
        setModulo(_modulo_);

        setPModv(_pModv_);

        setInteger(_integer_);

    }

    @Override
    public Object clone()
    {
        return new APModulo(
            cloneNode(this._modulo_),
            cloneNode(this._pModv_),
            cloneNode(this._integer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPModulo(this);
    }

    public TModulo getModulo()
    {
        return this._modulo_;
    }

    public void setModulo(TModulo node)
    {
        if(this._modulo_ != null)
        {
            this._modulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modulo_ = node;
    }

    public PPModv getPModv()
    {
        return this._pModv_;
    }

    public void setPModv(PPModv node)
    {
        if(this._pModv_ != null)
        {
            this._pModv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pModv_ = node;
    }

    public TInteger getInteger()
    {
        return this._integer_;
    }

    public void setInteger(TInteger node)
    {
        if(this._integer_ != null)
        {
            this._integer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._modulo_)
            + toString(this._pModv_)
            + toString(this._integer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._modulo_ == child)
        {
            this._modulo_ = null;
            return;
        }

        if(this._pModv_ == child)
        {
            this._pModv_ = null;
            return;
        }

        if(this._integer_ == child)
        {
            this._integer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._modulo_ == oldChild)
        {
            setModulo((TModulo) newChild);
            return;
        }

        if(this._pModv_ == oldChild)
        {
            setPModv((PPModv) newChild);
            return;
        }

        if(this._integer_ == oldChild)
        {
            setInteger((TInteger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
