/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class APSetxy extends PPSetxy
{
    private TSetxy _setxy_;
    private TInteger _x_;
    private TInteger _y_;

    public APSetxy()
    {
        // Constructor
    }

    public APSetxy(
        @SuppressWarnings("hiding") TSetxy _setxy_,
        @SuppressWarnings("hiding") TInteger _x_,
        @SuppressWarnings("hiding") TInteger _y_)
    {
        // Constructor
        setSetxy(_setxy_);

        setX(_x_);

        setY(_y_);

    }

    @Override
    public Object clone()
    {
        return new APSetxy(
            cloneNode(this._setxy_),
            cloneNode(this._x_),
            cloneNode(this._y_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPSetxy(this);
    }

    public TSetxy getSetxy()
    {
        return this._setxy_;
    }

    public void setSetxy(TSetxy node)
    {
        if(this._setxy_ != null)
        {
            this._setxy_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setxy_ = node;
    }

    public TInteger getX()
    {
        return this._x_;
    }

    public void setX(TInteger node)
    {
        if(this._x_ != null)
        {
            this._x_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x_ = node;
    }

    public TInteger getY()
    {
        return this._y_;
    }

    public void setY(TInteger node)
    {
        if(this._y_ != null)
        {
            this._y_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._y_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setxy_)
            + toString(this._x_)
            + toString(this._y_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setxy_ == child)
        {
            this._setxy_ = null;
            return;
        }

        if(this._x_ == child)
        {
            this._x_ = null;
            return;
        }

        if(this._y_ == child)
        {
            this._y_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setxy_ == oldChild)
        {
            setSetxy((TSetxy) newChild);
            return;
        }

        if(this._x_ == oldChild)
        {
            setX((TInteger) newChild);
            return;
        }

        if(this._y_ == oldChild)
        {
            setY((TInteger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
