/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ASethPSetheading extends PPSetheading
{
    private TSeth _seth_;
    private PPValue _pValue_;

    public ASethPSetheading()
    {
        // Constructor
    }

    public ASethPSetheading(
        @SuppressWarnings("hiding") TSeth _seth_,
        @SuppressWarnings("hiding") PPValue _pValue_)
    {
        // Constructor
        setSeth(_seth_);

        setPValue(_pValue_);

    }

    @Override
    public Object clone()
    {
        return new ASethPSetheading(
            cloneNode(this._seth_),
            cloneNode(this._pValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASethPSetheading(this);
    }

    public TSeth getSeth()
    {
        return this._seth_;
    }

    public void setSeth(TSeth node)
    {
        if(this._seth_ != null)
        {
            this._seth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seth_ = node;
    }

    public PPValue getPValue()
    {
        return this._pValue_;
    }

    public void setPValue(PPValue node)
    {
        if(this._pValue_ != null)
        {
            this._pValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._seth_)
            + toString(this._pValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._seth_ == child)
        {
            this._seth_ = null;
            return;
        }

        if(this._pValue_ == child)
        {
            this._pValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._seth_ == oldChild)
        {
            setSeth((TSeth) newChild);
            return;
        }

        if(this._pValue_ == oldChild)
        {
            setPValue((PPValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
