/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ASethsPGraphics extends PPGraphics
{
    private PPSetheading _pSetheading_;

    public ASethsPGraphics()
    {
        // Constructor
    }

    public ASethsPGraphics(
        @SuppressWarnings("hiding") PPSetheading _pSetheading_)
    {
        // Constructor
        setPSetheading(_pSetheading_);

    }

    @Override
    public Object clone()
    {
        return new ASethsPGraphics(
            cloneNode(this._pSetheading_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASethsPGraphics(this);
    }

    public PPSetheading getPSetheading()
    {
        return this._pSetheading_;
    }

    public void setPSetheading(PPSetheading node)
    {
        if(this._pSetheading_ != null)
        {
            this._pSetheading_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pSetheading_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pSetheading_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pSetheading_ == child)
        {
            this._pSetheading_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pSetheading_ == oldChild)
        {
            setPSetheading((PPSetheading) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
