/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class ASetheadingPSetheading extends PPSetheading
{
    private TSetheading _setheading_;

    public ASetheadingPSetheading()
    {
        // Constructor
    }

    public ASetheadingPSetheading(
        @SuppressWarnings("hiding") TSetheading _setheading_)
    {
        // Constructor
        setSetheading(_setheading_);

    }

    @Override
    public Object clone()
    {
        return new ASetheadingPSetheading(
            cloneNode(this._setheading_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASetheadingPSetheading(this);
    }

    public TSetheading getSetheading()
    {
        return this._setheading_;
    }

    public void setSetheading(TSetheading node)
    {
        if(this._setheading_ != null)
        {
            this._setheading_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setheading_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setheading_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setheading_ == child)
        {
            this._setheading_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setheading_ == oldChild)
        {
            setSetheading((TSetheading) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
