/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AThingPThingList extends PPThingList
{
    private PPThing _pThing_;

    public AThingPThingList()
    {
        // Constructor
    }

    public AThingPThingList(
        @SuppressWarnings("hiding") PPThing _pThing_)
    {
        // Constructor
        setPThing(_pThing_);

    }

    @Override
    public Object clone()
    {
        return new AThingPThingList(
            cloneNode(this._pThing_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAThingPThingList(this);
    }

    public PPThing getPThing()
    {
        return this._pThing_;
    }

    public void setPThing(PPThing node)
    {
        if(this._pThing_ != null)
        {
            this._pThing_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pThing_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pThing_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pThing_ == child)
        {
            this._pThing_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pThing_ == oldChild)
        {
            setPThing((PPThing) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
