/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class AToPWorkspace extends PPWorkspace
{
    private PPTo _pTo_;

    public AToPWorkspace()
    {
        // Constructor
    }

    public AToPWorkspace(
        @SuppressWarnings("hiding") PPTo _pTo_)
    {
        // Constructor
        setPTo(_pTo_);

    }

    @Override
    public Object clone()
    {
        return new AToPWorkspace(
            cloneNode(this._pTo_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAToPWorkspace(this);
    }

    public PPTo getPTo()
    {
        return this._pTo_;
    }

    public void setPTo(PPTo node)
    {
        if(this._pTo_ != null)
        {
            this._pTo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pTo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pTo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pTo_ == child)
        {
            this._pTo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pTo_ == oldChild)
        {
            setPTo((PPTo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
