/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TBf extends Token
{
    public TBf()
    {
        super.setText("BF");
    }

    public TBf(int line, int pos)
    {
        super.setText("BF");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBf(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBf text.");
    }
}
