/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TButfirst extends Token
{
    public TButfirst()
    {
        super.setText("BUTFIRST");
    }

    public TButfirst(int line, int pos)
    {
        super.setText("BUTFIRST");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TButfirst(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTButfirst(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TButfirst text.");
    }
}
