/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TClearscreen extends Token
{
    public TClearscreen()
    {
        super.setText("CLEARSCREEN");
    }

    public TClearscreen(int line, int pos)
    {
        super.setText("CLEARSCREEN");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TClearscreen(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTClearscreen(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TClearscreen text.");
    }
}
