/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TCs extends Token
{
    public TCs()
    {
        super.setText("CS");
    }

    public TCs(int line, int pos)
    {
        super.setText("CS");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCs(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCs(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCs text.");
    }
}
