/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TFirst extends Token
{
    public TFirst()
    {
        super.setText("FIRST");
    }

    public TFirst(int line, int pos)
    {
        super.setText("FIRST");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFirst(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFirst(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFirst text.");
    }
}
