/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TPenup extends Token
{
    public TPenup()
    {
        super.setText("PENUP");
    }

    public TPenup(int line, int pos)
    {
        super.setText("PENUP");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPenup(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPenup(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPenup text.");
    }
}
