/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TPush extends Token
{
    public TPush()
    {
        super.setText("PUSH");
    }

    public TPush(int line, int pos)
    {
        super.setText("PUSH");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPush(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPush(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPush text.");
    }
}
