/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TSetpensize extends Token
{
    public TSetpensize()
    {
        super.setText("SETPENSIZE");
    }

    public TSetpensize(int line, int pos)
    {
        super.setText("SETPENSIZE");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSetpensize(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSetpensize(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSetpensize text.");
    }
}
