/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.node;

import comp.logo.analysis.*;

@SuppressWarnings("nls")
public final class TSetxy extends Token
{
    public TSetxy()
    {
        super.setText("SETXY");
    }

    public TSetxy(int line, int pos)
    {
        super.setText("SETXY");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSetxy(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSetxy(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSetxy text.");
    }
}
