/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.analysis;

import java.util.*;
import comp.logo.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseAPWord(APWord node)
    {
        defaultCase(node);
    }

    public void caseAPList(APList node)
    {
        defaultCase(node);
    }

    public void caseAPFirst(APFirst node)
    {
        defaultCase(node);
    }

    public void caseAButfirstPButfirst(AButfirstPButfirst node)
    {
        defaultCase(node);
    }

    public void caseABfPButfirst(ABfPButfirst node)
    {
        defaultCase(node);
    }

    public void caseAPLast(APLast node)
    {
        defaultCase(node);
    }

    public void caseAPSetitem(APSetitem node)
    {
        defaultCase(node);
    }

    public void caseAPPush(APPush node)
    {
        defaultCase(node);
    }

    public void caseAPPop(APPop node)
    {
        defaultCase(node);
    }

    public void caseAPrintPPrint(APrintPPrint node)
    {
        defaultCase(node);
    }

    public void caseAPrPPrint(APrPPrint node)
    {
        defaultCase(node);
    }

    public void caseASumPSum(ASumPSum node)
    {
        defaultCase(node);
    }

    public void caseAPlusPSum(APlusPSum node)
    {
        defaultCase(node);
    }

    public void caseADifPDifference(ADifPDifference node)
    {
        defaultCase(node);
    }

    public void caseAMinPDifference(AMinPDifference node)
    {
        defaultCase(node);
    }

    public void caseAMinusPMinus(AMinusPMinus node)
    {
        defaultCase(node);
    }

    public void caseAMinPMinus(AMinPMinus node)
    {
        defaultCase(node);
    }

    public void caseAProdPProduct(AProdPProduct node)
    {
        defaultCase(node);
    }

    public void caseAMultPProduct(AMultPProduct node)
    {
        defaultCase(node);
    }

    public void caseAPModulo(APModulo node)
    {
        defaultCase(node);
    }

    public void caseAPInt(APInt node)
    {
        defaultCase(node);
    }

    public void caseAIdentListPIdentList(AIdentListPIdentList node)
    {
        defaultCase(node);
    }

    public void caseAIdentPIdentList(AIdentPIdentList node)
    {
        defaultCase(node);
    }

    public void caseAWordPThing(AWordPThing node)
    {
        defaultCase(node);
    }

    public void caseAListPThing(AListPThing node)
    {
        defaultCase(node);
    }

    public void caseAThingPThingList(AThingPThingList node)
    {
        defaultCase(node);
    }

    public void caseALstPThingList(ALstPThingList node)
    {
        defaultCase(node);
    }

    public void caseAIntPValue(AIntPValue node)
    {
        defaultCase(node);
    }

    public void caseADobPValue(ADobPValue node)
    {
        defaultCase(node);
    }

    public void caseAValueListPValueList(AValueListPValueList node)
    {
        defaultCase(node);
    }

    public void caseAValuePValueList(AValuePValueList node)
    {
        defaultCase(node);
    }

    public void caseASumValPSumList(ASumValPSumList node)
    {
        defaultCase(node);
    }

    public void caseASumListPSumList(ASumListPSumList node)
    {
        defaultCase(node);
    }

    public void caseADifValPDifList(ADifValPDifList node)
    {
        defaultCase(node);
    }

    public void caseADifListPDifList(ADifListPDifList node)
    {
        defaultCase(node);
    }

    public void caseAMultValPMultList(AMultValPMultList node)
    {
        defaultCase(node);
    }

    public void caseAMultListPMultList(AMultListPMultList node)
    {
        defaultCase(node);
    }

    public void caseAPModv(APModv node)
    {
        defaultCase(node);
    }

    public void caseAPRound(APRound node)
    {
        defaultCase(node);
    }

    public void caseAPSqrt(APSqrt node)
    {
        defaultCase(node);
    }

    public void caseAPPower(APPower node)
    {
        defaultCase(node);
    }

    public void caseAPExp(APExp node)
    {
        defaultCase(node);
    }

    public void caseASetheadingPSetheading(ASetheadingPSetheading node)
    {
        defaultCase(node);
    }

    public void caseASethPSetheading(ASethPSetheading node)
    {
        defaultCase(node);
    }

    public void caseAPHome(APHome node)
    {
        defaultCase(node);
    }

    public void caseAPArc(APArc node)
    {
        defaultCase(node);
    }

    public void caseAClearscreenPClearscreen(AClearscreenPClearscreen node)
    {
        defaultCase(node);
    }

    public void caseACsPClearscreen(ACsPClearscreen node)
    {
        defaultCase(node);
    }

    public void caseAPendownPPendown(APendownPPendown node)
    {
        defaultCase(node);
    }

    public void caseAPdPPendown(APdPPendown node)
    {
        defaultCase(node);
    }

    public void caseAPenupPPenup(APenupPPenup node)
    {
        defaultCase(node);
    }

    public void caseAPuPPenup(APuPPenup node)
    {
        defaultCase(node);
    }

    public void caseASetpencolorPSetpencolor(ASetpencolorPSetpencolor node)
    {
        defaultCase(node);
    }

    public void caseASetpcPSetpencolor(ASetpcPSetpencolor node)
    {
        defaultCase(node);
    }

    public void caseTWord(TWord node)
    {
        defaultCase(node);
    }

    public void caseTList(TList node)
    {
        defaultCase(node);
    }

    public void caseTFirst(TFirst node)
    {
        defaultCase(node);
    }

    public void caseTButfirst(TButfirst node)
    {
        defaultCase(node);
    }

    public void caseTBf(TBf node)
    {
        defaultCase(node);
    }

    public void caseTLast(TLast node)
    {
        defaultCase(node);
    }

    public void caseTSetitem(TSetitem node)
    {
        defaultCase(node);
    }

    public void caseTPush(TPush node)
    {
        defaultCase(node);
    }

    public void caseTPop(TPop node)
    {
        defaultCase(node);
    }

    public void caseTPrint(TPrint node)
    {
        defaultCase(node);
    }

    public void caseTPr(TPr node)
    {
        defaultCase(node);
    }

    public void caseTSum(TSum node)
    {
        defaultCase(node);
    }

    public void caseTDifference(TDifference node)
    {
        defaultCase(node);
    }

    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    public void caseTProduct(TProduct node)
    {
        defaultCase(node);
    }

    public void caseTModulo(TModulo node)
    {
        defaultCase(node);
    }

    public void caseTInt(TInt node)
    {
        defaultCase(node);
    }

    public void caseTRound(TRound node)
    {
        defaultCase(node);
    }

    public void caseTSqrt(TSqrt node)
    {
        defaultCase(node);
    }

    public void caseTPower(TPower node)
    {
        defaultCase(node);
    }

    public void caseTExp(TExp node)
    {
        defaultCase(node);
    }

    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    public void caseTNot(TNot node)
    {
        defaultCase(node);
    }

    public void caseTForward(TForward node)
    {
        defaultCase(node);
    }

    public void caseTFd(TFd node)
    {
        defaultCase(node);
    }

    public void caseTBack(TBack node)
    {
        defaultCase(node);
    }

    public void caseTBk(TBk node)
    {
        defaultCase(node);
    }

    public void caseTLeft(TLeft node)
    {
        defaultCase(node);
    }

    public void caseTLf(TLf node)
    {
        defaultCase(node);
    }

    public void caseTRight(TRight node)
    {
        defaultCase(node);
    }

    public void caseTRt(TRt node)
    {
        defaultCase(node);
    }

    public void caseTSetpos(TSetpos node)
    {
        defaultCase(node);
    }

    public void caseTSetxy(TSetxy node)
    {
        defaultCase(node);
    }

    public void caseTSetx(TSetx node)
    {
        defaultCase(node);
    }

    public void caseTSety(TSety node)
    {
        defaultCase(node);
    }

    public void caseTSetheading(TSetheading node)
    {
        defaultCase(node);
    }

    public void caseTSeth(TSeth node)
    {
        defaultCase(node);
    }

    public void caseTHome(THome node)
    {
        defaultCase(node);
    }

    public void caseTArc(TArc node)
    {
        defaultCase(node);
    }

    public void caseTClearscreen(TClearscreen node)
    {
        defaultCase(node);
    }

    public void caseTCs(TCs node)
    {
        defaultCase(node);
    }

    public void caseTPendown(TPendown node)
    {
        defaultCase(node);
    }

    public void caseTPd(TPd node)
    {
        defaultCase(node);
    }

    public void caseTPenup(TPenup node)
    {
        defaultCase(node);
    }

    public void caseTPu(TPu node)
    {
        defaultCase(node);
    }

    public void caseTSetpencolor(TSetpencolor node)
    {
        defaultCase(node);
    }

    public void caseTSetpc(TSetpc node)
    {
        defaultCase(node);
    }

    public void caseTSetpensize(TSetpensize node)
    {
        defaultCase(node);
    }

    public void caseTTo(TTo node)
    {
        defaultCase(node);
    }

    public void caseTMake(TMake node)
    {
        defaultCase(node);
    }

    public void caseTRun(TRun node)
    {
        defaultCase(node);
    }

    public void caseTRepeat(TRepeat node)
    {
        defaultCase(node);
    }

    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    public void caseTIfelse(TIfelse node)
    {
        defaultCase(node);
    }

    public void caseTStop(TStop node)
    {
        defaultCase(node);
    }

    public void caseTGoto(TGoto node)
    {
        defaultCase(node);
    }

    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    public void caseTLBrk(TLBrk node)
    {
        defaultCase(node);
    }

    public void caseTRBrk(TRBrk node)
    {
        defaultCase(node);
    }

    public void caseTLKey(TLKey node)
    {
        defaultCase(node);
    }

    public void caseTRKey(TRKey node)
    {
        defaultCase(node);
    }

    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    public void caseTMin(TMin node)
    {
        defaultCase(node);
    }

    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    public void caseTIdentifier(TIdentifier node)
    {
        defaultCase(node);
    }

    public void caseTInteger(TInteger node)
    {
        defaultCase(node);
    }

    public void caseTDouble(TDouble node)
    {
        defaultCase(node);
    }

    public void caseTNumber1(TNumber1 node)
    {
        defaultCase(node);
    }

    public void caseTEndline(TEndline node)
    {
        defaultCase(node);
    }

    public void caseTComment(TComment node)
    {
        defaultCase(node);
    }

    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
