/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp.logo.lexer;

import java.io.*;
import comp.logo.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 76:
                        {
                            @SuppressWarnings("hiding") Token token = new76(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 77:
                        {
                            @SuppressWarnings("hiding") Token token = new77(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 78:
                        {
                            @SuppressWarnings("hiding") Token token = new78(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcname(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWord(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TList(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFirst(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TButfirst(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBf(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLast(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetitem(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPush(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPop(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrint(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPr(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSum(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDifference(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProduct(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TModulo(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRound(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSqrt(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPower(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExp(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TForward(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFd(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBack(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBk(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeft(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLf(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRight(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRt(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetpos(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetxy(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetx(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSety(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetheading(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSeth(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THome(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArc(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClearscreen(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCs(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPendown(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPd(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPenup(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPu(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetpencolor(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetpc(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetpensize(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTo(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMake(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRun(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRepeat(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIfelse(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStop(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGoto(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnd(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrk(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrk(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLKey(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRKey(line, pos); }
    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMin(line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(line, pos); }
    Token new72(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new73(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new74(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteger(text, line, pos); }
    Token new75(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDouble(text, line, pos); }
    Token new76(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndline(text, line, pos); }
    Token new77(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new78(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{8, 8, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {35, 35, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 48, 14}, {49, 57, 15}, {59, 59, 16}, {65, 65, 17}, {66, 66, 18}, {67, 67, 19}, {68, 68, 20}, {69, 69, 21}, {70, 70, 22}, {71, 71, 23}, {72, 72, 24}, {73, 73, 25}, {74, 75, 26}, {76, 76, 27}, {77, 77, 28}, {78, 78, 29}, {79, 79, 30}, {80, 80, 31}, {81, 81, 26}, {82, 82, 32}, {83, 83, 33}, {84, 84, 34}, {85, 86, 26}, {87, 87, 35}, {88, 90, 26}, {91, 91, 36}, {93, 93, 37}, {95, 95, 38}, {97, 122, 39}, {123, 123, 40}, {125, 125, 41}, },
            {},
            {},
            {{10, 10, 42}, },
            {},
            {{0, 9, 43}, {10, 10, 44}, {11, 12, 43}, {13, 13, 45}, {14, 65535, 43}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 46}, },
            {},
            {{46, 46, 12}, {48, 57, 47}, },
            {{46, 46, 12}, {48, 57, 48}, },
            {},
            {{48, 57, 49}, {65, 77, 50}, {78, 78, 51}, {79, 81, 50}, {82, 82, 52}, {83, 90, 50}, {95, 95, 53}, {97, 122, 54}, },
            {{48, 57, 49}, {65, 65, 55}, {66, 69, 50}, {70, 70, 56}, {71, 74, 50}, {75, 75, 57}, {76, 84, 50}, {85, 85, 58}, {86, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 75, 50}, {76, 76, 59}, {77, 82, 50}, {83, 83, 60}, {84, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 72, 50}, {73, 73, 61}, {74, 90, 50}, {95, 122, -19}, },
            {{48, 77, -19}, {78, 78, 62}, {79, 87, 50}, {88, 88, 63}, {89, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 65, 64}, {66, 67, 50}, {68, 68, 65}, {69, 72, 50}, {73, 73, 66}, {74, 78, 50}, {79, 79, 67}, {80, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 78, 50}, {79, 79, 68}, {80, 122, -24}, },
            {{48, 78, -25}, {79, 79, 69}, {80, 122, -24}, },
            {{48, 57, 49}, {65, 69, 50}, {70, 70, 70}, {71, 77, 50}, {78, 78, 71}, {79, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 65, 72}, {66, 68, 50}, {69, 69, 73}, {70, 70, 74}, {71, 72, 50}, {73, 73, 75}, {74, 122, -22}, },
            {{48, 57, 49}, {65, 65, 76}, {66, 72, 50}, {73, 73, 77}, {74, 78, 50}, {79, 79, 78}, {80, 122, -24}, },
            {{48, 78, -25}, {79, 79, 79}, {80, 122, -24}, },
            {{48, 57, 49}, {65, 81, 50}, {82, 82, 80}, {83, 122, -19}, },
            {{48, 57, 49}, {65, 67, 50}, {68, 68, 81}, {69, 69, 82}, {70, 78, 50}, {79, 79, 83}, {80, 81, 50}, {82, 82, 84}, {83, 84, 50}, {85, 85, 85}, {86, 122, -20}, },
            {{48, 57, 49}, {65, 68, 50}, {69, 69, 86}, {70, 72, 50}, {73, 73, 87}, {74, 78, 50}, {79, 79, 88}, {80, 83, 50}, {84, 84, 89}, {85, 85, 90}, {86, 122, -20}, },
            {{48, 68, -34}, {69, 69, 91}, {70, 80, 50}, {81, 81, 92}, {82, 83, 50}, {84, 84, 93}, {85, 85, 94}, {86, 122, -20}, },
            {{48, 78, -25}, {79, 79, 95}, {80, 81, 50}, {82, 82, 96}, {83, 122, -19}, },
            {{48, 78, -25}, {79, 79, 97}, {80, 122, -24}, },
            {},
            {},
            {{48, 57, 98}, {65, 90, 99}, {97, 122, 100}, },
            {{48, 122, -28}, },
            {},
            {},
            {},
            {{0, 65535, -7}, },
            {},
            {{10, 10, 101}, },
            {{48, 57, 46}, },
            {{46, 57, -16}, },
            {{46, 57, -17}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 67, -33}, {68, 68, 102}, {69, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 66, 50}, {67, 67, 103}, {68, 90, 50}, {95, 122, -19}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 66, -54}, {67, 67, 104}, {68, 122, -54}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 57, 49}, {65, 83, 50}, {84, 84, 105}, {85, 90, 50}, {95, 122, -19}, },
            {{48, 68, -34}, {69, 69, 106}, {70, 90, 50}, {95, 122, -19}, },
            {{48, 122, -28}, },
            {{48, 69, -27}, {70, 70, 107}, {71, 90, 50}, {95, 122, -19}, },
            {{48, 67, -33}, {68, 68, 108}, {69, 122, -53}, },
            {{48, 57, 49}, {65, 79, 50}, {80, 80, 109}, {81, 90, 50}, {95, 122, -19}, },
            {{48, 75, -21}, {76, 76, 110}, {77, 90, 50}, {95, 122, -19}, },
            {{48, 122, -28}, },
            {{48, 81, -32}, {82, 82, 111}, {83, 122, -19}, },
            {{48, 81, -32}, {82, 82, 112}, {83, 122, -19}, },
            {{48, 83, -60}, {84, 84, 113}, {85, 122, -60}, },
            {{48, 57, 49}, {65, 76, 50}, {77, 77, 114}, {78, 90, 50}, {95, 122, -19}, },
            {{48, 68, -34}, {69, 69, 115}, {70, 122, -61}, },
            {{48, 83, -60}, {84, 84, 116}, {85, 122, -60}, },
            {{48, 57, 49}, {65, 82, 50}, {83, 83, 117}, {84, 122, -21}, },
            {{48, 69, -27}, {70, 70, 118}, {71, 122, -63}, },
            {{48, 122, -28}, },
            {{48, 82, -74}, {83, 83, 119}, {84, 122, -21}, },
            {{48, 57, 49}, {65, 74, 50}, {75, 75, 120}, {76, 90, 50}, {95, 122, -19}, },
            {{48, 77, -19}, {78, 78, 121}, {79, 122, -27}, },
            {{48, 67, -33}, {68, 68, 122}, {69, 122, -53}, },
            {{48, 83, -60}, {84, 84, 123}, {85, 122, -60}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 77, -19}, {78, 78, 124}, {79, 122, -27}, },
            {{48, 79, -65}, {80, 80, 125}, {81, 86, 50}, {87, 87, 126}, {88, 90, 50}, {95, 122, -19}, },
            {{48, 72, -22}, {73, 73, 127}, {74, 78, 50}, {79, 79, 128}, {80, 122, -24}, },
            {{48, 82, -74}, {83, 83, 129}, {84, 122, -21}, },
            {{48, 79, -65}, {80, 80, 130}, {81, 122, -65}, },
            {{48, 57, 49}, {65, 70, 50}, {71, 71, 131}, {72, 90, 50}, {95, 122, -19}, },
            {{48, 57, 49}, {65, 84, 50}, {85, 85, 132}, {86, 122, -20}, },
            {{48, 122, -28}, },
            {{48, 77, -19}, {78, 78, 133}, {79, 122, -27}, },
            {{48, 83, -60}, {84, 84, 134}, {85, 122, -60}, },
            {{48, 81, -32}, {82, 82, 135}, {83, 122, -19}, },
            {{48, 78, -25}, {79, 79, 136}, {80, 122, -24}, },
            {{48, 76, -71}, {77, 77, 137}, {78, 122, -71}, },
            {{48, 122, -28}, },
            {{48, 84, -90}, {85, 85, 138}, {86, 122, -20}, },
            {{48, 81, -32}, {82, 82, 139}, {83, 122, -19}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {},
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 74, -78}, {75, 75, 140}, {76, 122, -78}, },
            {{48, 69, -27}, {70, 70, 141}, {71, 122, -63}, },
            {{48, 57, 49}, {65, 65, 142}, {66, 90, 50}, {95, 122, -19}, },
            {{48, 69, -27}, {70, 70, 143}, {71, 122, -63}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 82, -74}, {83, 83, 144}, {84, 122, -21}, },
            {{48, 82, -74}, {83, 83, 145}, {84, 122, -21}, },
            {{48, 57, 49}, {65, 86, 50}, {87, 87, 146}, {88, 122, -85}, },
            {{48, 78, -25}, {79, 79, 147}, {80, 122, -24}, },
            {{48, 68, -34}, {69, 69, 148}, {70, 122, -61}, },
            {{48, 75, -21}, {76, 76, 149}, {77, 122, -66}, },
            {{48, 122, -28}, },
            {{48, 83, -60}, {84, 84, 150}, {85, 122, -60}, },
            {{48, 83, -60}, {84, 84, 151}, {85, 122, -60}, },
            {{48, 83, -60}, {84, 84, 152}, {85, 122, -60}, },
            {{48, 68, -34}, {69, 69, 153}, {70, 122, -61}, },
            {{48, 84, -90}, {85, 85, 154}, {86, 122, -20}, },
            {{48, 84, -90}, {85, 85, 155}, {86, 122, -20}, },
            {{48, 122, -28}, },
            {{48, 67, -33}, {68, 68, 156}, {69, 84, 50}, {85, 85, 157}, {86, 122, -20}, },
            {{48, 122, -28}, },
            {{48, 68, -34}, {69, 69, 158}, {70, 122, -61}, },
            {{48, 77, -19}, {78, 78, 159}, {79, 122, -27}, },
            {{48, 66, -54}, {67, 67, 160}, {68, 68, 161}, {69, 122, -53}, },
            {{48, 57, 49}, {65, 71, 50}, {72, 72, 162}, {73, 90, 50}, {95, 122, -19}, },
            {{48, 68, -34}, {69, 69, 163}, {70, 122, -61}, },
            {{48, 71, -131}, {72, 72, 164}, {73, 122, -131}, },
            {{48, 77, -19}, {78, 78, 165}, {79, 122, -27}, },
            {{48, 122, -28}, },
            {{48, 71, -131}, {72, 72, 166}, {73, 73, 167}, {74, 79, 50}, {80, 80, 168}, {81, 87, 50}, {88, 88, 169}, {89, 89, 170}, {90, 90, 50}, {95, 122, -19}, },
            {{48, 83, -60}, {84, 84, 171}, {85, 122, -60}, },
            {{48, 79, -65}, {80, 80, 172}, {81, 122, -65}, },
            {{48, 122, -28}, },
            {{48, 68, -34}, {69, 69, 173}, {70, 122, -61}, },
            {{48, 67, -33}, {68, 68, 174}, {69, 122, -53}, },
            {{48, 122, -28}, },
            {{48, 72, -22}, {73, 73, 175}, {74, 122, -22}, },
            {{48, 81, -32}, {82, 82, 176}, {83, 122, -19}, },
            {{48, 68, -34}, {69, 69, 177}, {70, 122, -61}, },
            {{48, 68, -34}, {69, 69, 178}, {70, 122, -61}, },
            {{48, 83, -60}, {84, 84, 179}, {85, 122, -60}, },
            {{48, 57, 49}, {65, 65, 180}, {66, 122, -108}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 82, -74}, {83, 83, 181}, {84, 122, -21}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 82, -74}, {83, 83, 182}, {84, 122, -21}, },
            {{48, 75, -21}, {76, 76, 183}, {77, 122, -66}, },
            {{48, 78, -25}, {79, 79, 184}, {80, 122, -24}, },
            {{48, 79, -65}, {80, 80, 185}, {81, 122, -65}, },
            {{48, 81, -32}, {82, 82, 186}, {83, 122, -19}, },
            {{48, 83, -60}, {84, 84, 187}, {85, 122, -60}, },
            {{48, 77, -19}, {78, 78, 188}, {79, 122, -27}, },
            {{48, 84, -90}, {85, 85, 189}, {86, 122, -20}, },
            {{48, 122, -28}, },
            {{48, 57, 49}, {65, 65, 190}, {66, 122, -108}, },
            {{48, 83, -60}, {84, 84, 191}, {85, 122, -60}, },
            {{48, 67, -33}, {68, 68, 192}, {69, 122, -53}, },
            {{48, 68, -34}, {69, 69, 193}, {70, 122, -61}, },
            {{48, 83, -60}, {84, 84, 194}, {85, 122, -60}, },
            {{48, 66, -54}, {67, 67, 195}, {68, 68, 50}, {69, 69, 196}, {70, 78, 50}, {79, 79, 197}, {80, 122, -24}, },
            {{48, 57, 49}, {65, 88, 50}, {89, 89, 198}, {90, 122, -136}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 81, -32}, {82, 82, 199}, {83, 122, -19}, },
            {{48, 82, -74}, {83, 83, 200}, {84, 122, -21}, },
            {{48, 81, -32}, {82, 82, 201}, {83, 122, -19}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 81, -32}, {82, 82, 202}, {83, 122, -19}, },
            {{48, 68, -34}, {69, 69, 203}, {70, 122, -61}, },
            {{48, 122, -28}, },
            {{48, 78, -25}, {79, 79, 204}, {80, 122, -24}, },
            {{48, 86, -114}, {87, 87, 205}, {88, 122, -85}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 57, 49}, {65, 65, 206}, {66, 122, -108}, },
            {{48, 66, -54}, {67, 67, 207}, {68, 122, -54}, },
            {{48, 83, -60}, {84, 84, 208}, {85, 122, -60}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 57, 49}, {65, 65, 209}, {66, 122, -108}, },
            {{48, 68, -34}, {69, 69, 210}, {70, 122, -61}, },
            {{48, 122, -28}, },
            {{48, 77, -19}, {78, 78, 211}, {79, 122, -27}, },
            {{48, 82, -74}, {83, 83, 212}, {84, 122, -21}, },
            {{48, 122, -28}, },
            {{48, 82, -74}, {83, 83, 213}, {84, 122, -21}, },
            {{48, 66, -54}, {67, 67, 214}, {68, 122, -54}, },
            {{48, 68, -34}, {69, 69, 215}, {70, 122, -61}, },
            {{48, 67, -33}, {68, 68, 216}, {69, 122, -53}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 77, -19}, {78, 78, 217}, {79, 122, -27}, },
            {{48, 76, -71}, {77, 77, 218}, {78, 122, -71}, },
            {{48, 83, -60}, {84, 84, 219}, {85, 122, -60}, },
            {{48, 122, -28}, },
            {{48, 67, -33}, {68, 68, 220}, {69, 122, -53}, },
            {{48, 76, -71}, {77, 77, 221}, {78, 122, -71}, },
            {{48, 66, -54}, {67, 67, 222}, {68, 82, 50}, {83, 83, 223}, {84, 122, -21}, },
            {{48, 122, -28}, },
            {{48, 83, -60}, {84, 84, 224}, {85, 122, -60}, },
            {{48, 81, -32}, {82, 82, 225}, {83, 122, -19}, },
            {{48, 77, -19}, {78, 78, 226}, {79, 122, -27}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 68, -34}, {69, 69, 227}, {70, 122, -61}, },
            {{48, 122, -28}, },
            {{48, 72, -22}, {73, 73, 228}, {74, 122, -22}, },
            {{48, 122, -28}, },
            {{48, 78, -25}, {79, 79, 229}, {80, 122, -24}, },
            {{48, 72, -22}, {73, 73, 230}, {74, 122, -22}, },
            {{48, 122, -28}, },
            {{48, 68, -34}, {69, 69, 231}, {70, 122, -61}, },
            {{48, 66, -54}, {67, 67, 232}, {68, 122, -54}, },
            {{48, 122, -28}, },
            {{48, 77, -19}, {78, 78, 233}, {79, 122, -27}, },
            {{48, 75, -21}, {76, 76, 234}, {77, 122, -66}, },
            {{48, 57, 49}, {65, 89, 50}, {90, 90, 235}, {95, 122, -19}, },
            {{48, 68, -34}, {69, 69, 236}, {70, 122, -61}, },
            {{48, 68, -34}, {69, 69, 237}, {70, 122, -61}, },
            {{48, 70, -89}, {71, 71, 238}, {72, 122, -89}, },
            {{48, 78, -25}, {79, 79, 239}, {80, 122, -24}, },
            {{48, 68, -34}, {69, 69, 240}, {70, 122, -61}, },
            {{48, 77, -19}, {78, 78, 241}, {79, 122, -27}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 81, -32}, {82, 82, 242}, {83, 122, -19}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {76, 78, 76, 76, 78, 77, 61, 62, 70, 67, 72, 68, -1, 69, 74, 74, 71, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 63, 64, -1, 73, 65, 66, 76, 77, 77, 77, 75, -1, 74, 73, 73, 73, 73, 73, 73, 73, 5, 28, 73, 73, 42, 73, 73, 73, 73, 26, 73, 73, 73, 73, 54, 73, 73, 73, 30, 73, 73, 73, 73, 73, 23, 44, 73, 73, 11, 46, 73, 73, 73, 32, 73, 73, 73, 73, 73, 50, 73, 73, 73, 73, 73, 77, 22, 40, 73, 73, 73, 73, 58, 21, 73, 73, 73, 73, 73, 73, 17, 73, 73, 73, 73, 73, 73, 24, 73, 9, 73, 73, 73, 73, 73, 73, 73, 52, 73, 73, 73, 12, 73, 73, 27, 73, 73, 73, 73, 73, 73, 57, 39, 73, 6, 29, 2, 51, 73, 73, 73, 73, 73, 73, 73, 73, 8, 73, 73, 73, 38, 73, 73, 35, 36, 19, 56, 59, 1, 73, 73, 73, 60, 3, 73, 73, 14, 73, 73, 45, 20, 10, 73, 73, 73, 31, 18, 73, 73, 48, 73, 73, 34, 73, 73, 73, 73, 55, 16, 73, 73, 73, 53, 73, 73, 73, 33, 73, 73, 73, 25, 43, 73, 15, 73, 7, 73, 73, 4, 73, 73, 0, 73, 73, 73, 73, 73, 73, 73, 73, 73, 13, 37, 73, 49, 41, 47, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
